apiVersion: v1
kind: ConfigMap
metadata:
  name: whereabouts-config
  namespace: openshift-multus
data:
  whereabouts.conf: |
    {"datastore":"kubernetes","kubernetes":{"kubeconfig":"/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig"},"configuration_path":"/etc/cni/net.d/whereabouts.d","reconciler_cron_expression":"30 4 * * *"}
  reconciler_cron_expression: "30 4 * * *"
